[project]
name = "water-monitor"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "RPi.GPIO",
    "rich",
    "simpleaudio",
    "pydub"
]

[project.scripts]
water-monitor = "water_monitor.main:main"
play-sound = "water_monitor.play_sound:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
